services:
  controle-estoque-db:
    image: bitnami/postgresql
    container_name: controle-estoque-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: controle-estoque-db
  api:
    image: thiago0503/controle-estoque-api:v1
    ports:
      - 4000:4000
    env_file: .env
