name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and push"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm i -g pnpm

      - name: "Generate tag"
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      - name: "Login into the container registry"
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: "Build and Push"
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thiago0503/controle-estoque-api:${{steps.generate_tag.outputs.sha}}, thiago0503/controle-estoque-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image docker hub
        run: docker pull thiago0503/security-app:latest
      - name: remove container
        run: docker rm -f security-app
      - name: Run docker container
        run: docker run -d -p 4000:4000 -e DATABASE_URL='${{secrets.DATABASE_URL}}' -e JWT_SECRET='${{secrets.JWT_SECRET}}' --name security-app thiago0503/security-app:latest
